#ifndef SET_H
#define SET_H

#include <cstddef>
#include <string>
#include "Node.h"

// This is the Set class you need to implement.
// You don't need to use mCount if you don't want to.
// Do not edit this file.

class Set {
  Node*  mRoot;
  size_t mCount;

public:
  Set();
  Set(const Set& other);
  Set(Set&& other);
  ~Set();

  size_t clear();
  bool   contains(const std::string& value) const;
  size_t count() const;
  void   debug();
  size_t insert(const std::string& value);
  void   print() const;
  size_t remove(const std::string& value);
  bool   swivel(const std::string& value);

  // Used by the autograder:
  const Node* root() const {
    return mRoot;
  }
};

#endif
